export const RECEIVE_SUCCESS_MESSAGE = 'alert/RECEIVE_SUCCESS_MESSAGE';
export const RECEIVE_ERRORS_MESSAGE = 'alert/RECEIVE_ERRORS_MESSAGE';
export const RECEIVE_ERROR_MESSAGE = 'alert/RECEIVE_ERROR_MESSAGE';
