export const REQUEST_REGISTER = 'auth/REQUEST_REGISTER';
export const RECEIVE_LOGIN = 'auth/RECEIVE_LOGIN';


export const REQUEST_REGISTER_AUTH = 'REQUEST_REGISTER_AUTH';
export const REQUEST_LOGIN_AUTH = 'REQUEST_LOGIN_AUTH';

export const RE_REQUEST_LOGIN_AUTH = 'RE_REQUEST_LOGIN_AUTH';
export const REQUEST_LOGOUT_AUTH = 'REQUEST_LOGOUT_AUTH';
export const REQUEST_CURRENT_USER = 'REQUEST_CURRENT_USER';
export const RECEIVE_CURRENT_USER = 'RECEIVE_CURRENT_USER';

// export const USER_REQUEST = 'USER_REQUEST'
// export const USER_SUCCESS = 'USER_SUCCESS'
// export const USER_FAILURE = 'USER_FAILURE'
